"""cv_schema_isolation_and_partitioning

Revision ID: 400796689aa4
Revises: f3675cb5bc88
Create Date: 2026-02-20 09:33:18.544651+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '400796689aa4'
down_revision = 'f3675cb5bc88'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('branches',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('peak_time', sa.String(length=10), nullable=True),
    sa.Column('neighbors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('state', sa.String(length=50), nullable=True),
    sa.Column('expiry', sa.DateTime(), nullable=True),
    sa.Column('restocking_schedule', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_branches')),
    schema='core'
    )
    op.create_table('customers',
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('customer_id', name=op.f('pk_customers')),
    schema='core'
    )
    op.create_table('employees',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('position', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_employees')),
    schema='core'
    )
    op.create_table('events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('type', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('location', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('repetition', sa.String(length=50), nullable=True),
    sa.Column('global_event', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_events')),
    schema='core'
    )
    op.create_index('ix_events_start_time', 'events', ['start_time'], unique=False, schema='core')
    op.create_index('ix_events_type', 'events', ['type'], unique=False, schema='core')
    op.create_table('branch_daily_metrics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('branch_id', sa.String(length=100), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('total_entries', sa.Integer(), nullable=True),
    sa.Column('avg_dwell_time', sa.Float(), nullable=True),
    sa.Column('conversion_rate', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['core.branches.id'], name=op.f('fk_branch_daily_metrics_branch_id_branches')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_branch_daily_metrics')),
    sa.UniqueConstraint('branch_id', 'date', name='uq_branch_daily_metrics_branch_date'),
    schema='core'
    )
    op.create_index('ix_branch_daily_metrics_branch_id', 'branch_daily_metrics', ['branch_id'], unique=False, schema='core')
    op.create_index('ix_branch_daily_metrics_date', 'branch_daily_metrics', ['date'], unique=False, schema='core')
    op.create_table('branch_kpi_timeseries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('branch_id', sa.String(length=100), nullable=False),
    sa.Column('time_window_start', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('time_window_end', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('traffic_index', sa.Float(), nullable=True),
    sa.Column('conversion_proxy', sa.Float(), nullable=True),
    sa.Column('congestion_level', sa.Float(), nullable=True),
    sa.Column('growth_momentum', sa.Float(), nullable=True),
    sa.Column('utilization_ratio', sa.Float(), nullable=True),
    sa.Column('staffing_adequacy_index', sa.Float(), nullable=True),
    sa.Column('bottleneck_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['core.branches.id'], name=op.f('fk_branch_kpi_timeseries_branch_id_branches')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_branch_kpi_timeseries')),
    schema='core'
    )
    op.create_index('ix_branch_kpi_timeseries_branch_id', 'branch_kpi_timeseries', ['branch_id'], unique=False, schema='core')
    op.create_index('ix_branch_kpi_timeseries_branch_id_time_window', 'branch_kpi_timeseries', ['branch_id', 'time_window_start'], unique=False, schema='core')
    op.create_index('ix_branch_kpi_timeseries_time_window_start', 'branch_kpi_timeseries', ['time_window_start'], unique=False, schema='core')
    op.create_table('customer_branch_movement',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('branch_id', sa.String(length=100), nullable=False),
    sa.Column('enter_time', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('exit_time', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('action_type', sa.Enum('PASSED', 'ENTERED', name='actiontype'), nullable=False),
    sa.Column('event_hash', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['core.branches.id'], name=op.f('fk_customer_branch_movement_branch_id_branches')),
    sa.ForeignKeyConstraint(['customer_id'], ['core.customers.customer_id'], name=op.f('fk_customer_branch_movement_customer_id_customers')),
    sa.PrimaryKeyConstraint('id', 'enter_time', name=op.f('pk_customer_branch_movement')),
    sa.UniqueConstraint('event_hash', 'enter_time', name='uq_customer_branch_movement_event_hash'),
    schema='core',
    postgresql_partition_by='RANGE (enter_time)'
    )
    op.create_index('ix_customer_branch_movement_branch_id', 'customer_branch_movement', ['branch_id'], unique=False, schema='core')
    op.create_index('ix_customer_branch_movement_branch_id_enter_time', 'customer_branch_movement', ['branch_id', 'enter_time'], unique=False, schema='core')
    op.create_index('ix_customer_branch_movement_enter_time', 'customer_branch_movement', ['enter_time'], unique=False, schema='core')
    op.create_index('ix_customer_branch_movement_exit_time', 'customer_branch_movement', ['exit_time'], unique=False, schema='core')
    op.create_table('promotions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('branch_id', sa.String(length=100), nullable=True),
    sa.Column('item_name', sa.String(length=200), nullable=True),
    sa.Column('promotion_type', sa.String(length=100), nullable=False),
    sa.Column('discount_value', sa.Float(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['core.branches.id'], name=op.f('fk_promotions_branch_id_branches')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_promotions')),
    schema='core'
    )
    op.create_index('ix_promotions_branch_id', 'promotions', ['branch_id'], unique=False, schema='core')
    op.create_index('ix_promotions_start_date', 'promotions', ['start_date'], unique=False, schema='core')
    op.create_table('situations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('branch_id', sa.String(length=100), nullable=False),
    sa.Column('situation_label', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.Float(), nullable=False),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('detected_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['core.branches.id'], name=op.f('fk_situations_branch_id_branches')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_situations')),
    schema='core'
    )
    op.create_table('staff',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('branch_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=100), nullable=False),
    sa.Column('shift_start', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('shift_end', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['core.branches.id'], name=op.f('fk_staff_branch_id_branches')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_staff')),
    schema='core'
    )
    op.create_table('recommendations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('situation_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('priority', sa.String(length=50), nullable=False),
    sa.Column('expected_impact', sa.Text(), nullable=True),
    sa.Column('value_factor', sa.Float(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['situation_id'], ['core.situations.id'], name=op.f('fk_recommendations_situation_id_situations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recommendations')),
    schema='core'
    )
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('recommendation_id', sa.Integer(), nullable=True),
    sa.Column('task', sa.Text(), nullable=False),
    sa.Column('time', sa.DateTime(), nullable=False),
    sa.Column('state', sa.String(length=50), nullable=False),
    sa.Column('branch_id', sa.String(length=100), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['core.branches.id'], name=op.f('fk_tasks_branch_id_branches')),
    sa.ForeignKeyConstraint(['employee_id'], ['core.employees.id'], name=op.f('fk_tasks_employee_id_employees')),
    sa.ForeignKeyConstraint(['recommendation_id'], ['core.recommendations.id'], name=op.f('fk_tasks_recommendation_id_recommendations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tasks')),
    schema='core'
    )
    op.create_index('ix_tasks_branch_id', 'tasks', ['branch_id'], unique=False, schema='core')
    op.create_index('ix_tasks_employee_id', 'tasks', ['employee_id'], unique=False, schema='core')
    op.create_index('ix_tasks_time', 'tasks', ['time'], unique=False, schema='core')
    op.drop_index('ix_nlp_queries_log_conversation_id', table_name='nlp_queries_log')
    op.drop_index('ix_nlp_queries_log_created_at', table_name='nlp_queries_log')
    op.drop_index('ix_nlp_queries_log_intent', table_name='nlp_queries_log')
    op.drop_table('nlp_queries_log')
    op.drop_table('situations')
    op.drop_index('ix_customer_branch_movement_branch_id', table_name='customer_branch_movement')
    op.drop_index('ix_customer_branch_movement_branch_id_enter_time', table_name='customer_branch_movement')
    op.drop_index('ix_customer_branch_movement_enter_time', table_name='customer_branch_movement')
    op.drop_index('ix_customer_branch_movement_exit_time', table_name='customer_branch_movement')
    op.drop_table('customer_branch_movement')
    op.drop_table('recommendations')
    op.drop_index('ix_tasks_branch_id', table_name='tasks')
    op.drop_index('ix_tasks_employee_id', table_name='tasks')
    op.drop_index('ix_tasks_time', table_name='tasks')
    op.drop_table('tasks')
    op.drop_table('alembic_version_nlp')
    op.drop_table('employees')
    op.drop_table('staff')
    op.drop_index('ix_promotions_branch_id', table_name='promotions')
    op.drop_index('ix_promotions_start_date', table_name='promotions')
    op.drop_table('promotions')
    op.drop_index('ix_events_start_time', table_name='events')
    op.drop_index('ix_events_type', table_name='events')
    op.drop_table('events')
    op.drop_table('customers')
    op.drop_index('ix_nlp_feedback_query_id', table_name='nlp_feedback')
    op.drop_table('nlp_feedback')
    op.drop_table('alembic_version')
    op.drop_table('branches')
    op.drop_index('ix_branch_kpi_timeseries_branch_id', table_name='branch_kpi_timeseries')
    op.drop_index('ix_branch_kpi_timeseries_branch_id_time_window', table_name='branch_kpi_timeseries')
    op.drop_index('ix_branch_kpi_timeseries_time_window_start', table_name='branch_kpi_timeseries')
    op.drop_table('branch_kpi_timeseries')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('branch_kpi_timeseries',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('branch_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('time_window_start', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('time_window_end', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('traffic_index', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('conversion_proxy', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('congestion_level', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('growth_momentum', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('utilization_ratio', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('staffing_adequacy_index', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('bottleneck_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name='fk_branch_kpi_timeseries_branch_id_branches'),
    sa.PrimaryKeyConstraint('id', name='pk_branch_kpi_timeseries')
    )
    op.create_index('ix_branch_kpi_timeseries_time_window_start', 'branch_kpi_timeseries', ['time_window_start'], unique=False)
    op.create_index('ix_branch_kpi_timeseries_branch_id_time_window', 'branch_kpi_timeseries', ['branch_id', 'time_window_start'], unique=False)
    op.create_index('ix_branch_kpi_timeseries_branch_id', 'branch_kpi_timeseries', ['branch_id'], unique=False)
    op.create_table('branches',
    sa.Column('id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('capacity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('peak_time', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('neighbors', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('state', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('expiry', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('restocking_schedule', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='pk_branches'),
    postgresql_ignore_search_path=False
    )
    op.create_table('alembic_version',
    sa.Column('version_num', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('version_num', name='alembic_version_pkc')
    )
    op.create_table('nlp_feedback',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('query_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('rating', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('comment', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['query_id'], ['nlp_queries_log.id'], name='fk_nlp_feedback_query_id_nlp_queries_log', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='pk_nlp_feedback')
    )
    op.create_index('ix_nlp_feedback_query_id', 'nlp_feedback', ['query_id'], unique=False)
    op.create_table('customers',
    sa.Column('customer_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('customer_id', name='pk_customers'),
    postgresql_ignore_search_path=False
    )
    op.create_table('events',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('start_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('end_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('type', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('location', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('repetition', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('global_event', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='pk_events')
    )
    op.create_index('ix_events_type', 'events', ['type'], unique=False)
    op.create_index('ix_events_start_time', 'events', ['start_time'], unique=False)
    op.create_table('promotions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('branch_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('item_name', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('promotion_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('discount_value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('start_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('end_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name='fk_promotions_branch_id_branches'),
    sa.PrimaryKeyConstraint('id', name='pk_promotions')
    )
    op.create_index('ix_promotions_start_date', 'promotions', ['start_date'], unique=False)
    op.create_index('ix_promotions_branch_id', 'promotions', ['branch_id'], unique=False)
    op.create_table('staff',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('branch_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('shift_start', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('shift_end', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name='fk_staff_branch_id_branches'),
    sa.PrimaryKeyConstraint('id', name='pk_staff')
    )
    op.create_table('employees',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('employees_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('position', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('phone', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='pk_employees'),
    postgresql_ignore_search_path=False
    )
    op.create_table('alembic_version_nlp',
    sa.Column('version_num', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('version_num', name='alembic_version_nlp_pkc')
    )
    op.create_table('tasks',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('task', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('state', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('branch_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('note', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('recommendation_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name='fk_tasks_branch_id_branches'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name='fk_tasks_employee_id_employees'),
    sa.ForeignKeyConstraint(['recommendation_id'], ['recommendations.id'], name='fk_tasks_recommendation_id_recommendations'),
    sa.PrimaryKeyConstraint('id', name='pk_tasks')
    )
    op.create_index('ix_tasks_time', 'tasks', ['time'], unique=False)
    op.create_index('ix_tasks_employee_id', 'tasks', ['employee_id'], unique=False)
    op.create_index('ix_tasks_branch_id', 'tasks', ['branch_id'], unique=False)
    op.create_table('recommendations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('situation_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('action', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('priority', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('expected_impact', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('value_factor', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['situation_id'], ['situations.id'], name='fk_recommendations_situation_id_situations'),
    sa.PrimaryKeyConstraint('id', name='pk_recommendations')
    )
    op.create_table('customer_branch_movement',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('customer_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('branch_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('enter_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('exit_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('action_type', postgresql.ENUM('PASSED', 'ENTERED', name='actiontype'), autoincrement=False, nullable=False),
    sa.Column('event_hash', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name='fk_customer_branch_movement_branch_id_branches'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.customer_id'], name='fk_customer_branch_movement_customer_id_customers'),
    sa.PrimaryKeyConstraint('id', name='pk_customer_branch_movement'),
    sa.UniqueConstraint('event_hash', name='uq_customer_branch_movement_event_hash')
    )
    op.create_index('ix_customer_branch_movement_exit_time', 'customer_branch_movement', ['exit_time'], unique=False)
    op.create_index('ix_customer_branch_movement_enter_time', 'customer_branch_movement', ['enter_time'], unique=False)
    op.create_index('ix_customer_branch_movement_branch_id_enter_time', 'customer_branch_movement', ['branch_id', 'enter_time'], unique=False)
    op.create_index('ix_customer_branch_movement_branch_id', 'customer_branch_movement', ['branch_id'], unique=False)
    op.create_table('situations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('branch_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('situation_label', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('severity', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('details', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('detected_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name='fk_situations_branch_id_branches'),
    sa.PrimaryKeyConstraint('id', name='pk_situations')
    )
    op.create_table('nlp_queries_log',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('conversation_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_role', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('query_text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('intent', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('confidence', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('routed_endpoint', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='pk_nlp_queries_log')
    )
    op.create_index('ix_nlp_queries_log_intent', 'nlp_queries_log', ['intent'], unique=False)
    op.create_index('ix_nlp_queries_log_created_at', 'nlp_queries_log', ['created_at'], unique=False)
    op.create_index('ix_nlp_queries_log_conversation_id', 'nlp_queries_log', ['conversation_id'], unique=False)
    op.drop_index('ix_tasks_time', table_name='tasks', schema='core')
    op.drop_index('ix_tasks_employee_id', table_name='tasks', schema='core')
    op.drop_index('ix_tasks_branch_id', table_name='tasks', schema='core')
    op.drop_table('tasks', schema='core')
    op.drop_table('recommendations', schema='core')
    op.drop_table('staff', schema='core')
    op.drop_table('situations', schema='core')
    op.drop_index('ix_promotions_start_date', table_name='promotions', schema='core')
    op.drop_index('ix_promotions_branch_id', table_name='promotions', schema='core')
    op.drop_table('promotions', schema='core')
    op.drop_index('ix_customer_branch_movement_exit_time', table_name='customer_branch_movement', schema='core')
    op.drop_index('ix_customer_branch_movement_enter_time', table_name='customer_branch_movement', schema='core')
    op.drop_index('ix_customer_branch_movement_branch_id_enter_time', table_name='customer_branch_movement', schema='core')
    op.drop_index('ix_customer_branch_movement_branch_id', table_name='customer_branch_movement', schema='core')
    op.drop_table('customer_branch_movement', schema='core')
    op.drop_index('ix_branch_kpi_timeseries_time_window_start', table_name='branch_kpi_timeseries', schema='core')
    op.drop_index('ix_branch_kpi_timeseries_branch_id_time_window', table_name='branch_kpi_timeseries', schema='core')
    op.drop_index('ix_branch_kpi_timeseries_branch_id', table_name='branch_kpi_timeseries', schema='core')
    op.drop_table('branch_kpi_timeseries', schema='core')
    op.drop_index('ix_branch_daily_metrics_date', table_name='branch_daily_metrics', schema='core')
    op.drop_index('ix_branch_daily_metrics_branch_id', table_name='branch_daily_metrics', schema='core')
    op.drop_table('branch_daily_metrics', schema='core')
    op.drop_index('ix_events_type', table_name='events', schema='core')
    op.drop_index('ix_events_start_time', table_name='events', schema='core')
    op.drop_table('events', schema='core')
    op.drop_table('employees', schema='core')
    op.drop_table('customers', schema='core')
    op.drop_table('branches', schema='core')
    # ### end Alembic commands ###
