"""Add staff situation recommendation tables and indexes

Revision ID: f3675cb5bc88
Revises: 001
Create Date: 2026-02-20 08:55:05.016171+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f3675cb5bc88'
down_revision = '001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('situations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('branch_id', sa.String(length=100), nullable=False),
    sa.Column('situation_label', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.Float(), nullable=False),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('detected_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name=op.f('fk_situations_branch_id_branches')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_situations'))
    )
    op.create_table('staff',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('branch_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=100), nullable=False),
    sa.Column('shift_start', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('shift_end', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name=op.f('fk_staff_branch_id_branches')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_staff'))
    )
    op.create_table('recommendations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('situation_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('priority', sa.String(length=50), nullable=False),
    sa.Column('expected_impact', sa.Text(), nullable=True),
    sa.Column('value_factor', sa.Float(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['situation_id'], ['situations.id'], name=op.f('fk_recommendations_situation_id_situations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recommendations'))
    )
    op.add_column('customer_branch_movement', sa.Column('event_hash', sa.String(length=64), nullable=True))
    op.create_index('ix_customer_branch_movement_branch_id', 'customer_branch_movement', ['branch_id'], unique=False)
    op.create_unique_constraint(op.f('uq_customer_branch_movement_event_hash'), 'customer_branch_movement', ['event_hash'])
    op.add_column('tasks', sa.Column('recommendation_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_tasks_recommendation_id_recommendations'), 'tasks', 'recommendations', ['recommendation_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_tasks_recommendation_id_recommendations'), 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'recommendation_id')
    op.drop_constraint(op.f('uq_customer_branch_movement_event_hash'), 'customer_branch_movement', type_='unique')
    op.drop_index('ix_customer_branch_movement_branch_id', table_name='customer_branch_movement')
    op.drop_column('customer_branch_movement', 'event_hash')
    op.drop_table('recommendations')
    op.drop_table('staff')
    op.drop_table('situations')
    # ### end Alembic commands ###
